### ISSUE TITLE
Wrong github user in README tutorial

### ISSUE THREAD

**Issue by curtismuntz** [resin-io-projects/multicontainer-getting-started#4]
In README.md, `git clone git@github.com:resin-projects/multicontainer-getting-started.git` is pointing to the wrong github user and fails to clone the repo.

I'm guessing it should be `resin-io-projects`

Great work on multicontainer! It's working great so far.

**Comment by zwalchuk** [comment]
@curtismuntz thanks for pointing that out! Fixed now.
